id: P8A006550
initial_creation_type: input
source_metadata:
  title: Mīmāṃsāsūtra 1-7 with Śabara's Bhāṣya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Mīmāṃsā
  data entry: Andreas Pohlus
  contribution to GRETIL: Andreas Pohlus
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:53:18.510377'
last_modified_at: '2022-03-09T14:53:18.510391'
